### ISSUE TITLE
Prepare the application for deployment in vercel

### ISSUE THREAD

**Issue by ravend3v** [ravend3v/restaurant-app#15]
### Description

We need to set up an automated deployment process using GitHub Actions to deploy our application to Vercel whenever changes are merged to the `main` branch. Please follow the steps below to configure the workflow:

1. **Create GitHub Actions Workflow:**
   - Create a new workflow file `.github/workflows/deploy.yml`.
   - Define the workflow to trigger on `push` events to the `main` branch.

2. **Set Up Vercel Token:**
   - Generate a Vercel token from the Vercel dashboard.
   - Add the Vercel token as a secret in the GitHub repository settings (`Settings > Secrets > Actions`).

3. **Configure the Workflow:**
   - Configure the workflow to use the Vercel token for authentication.
   - Add steps to check out the repository, install dependencies, build the application, and deploy to Vercel.

### Sample Workflow Configuration

```yaml name=.github/workflows/deploy.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN
```

### Acceptance Criteria

- A GitHub Actions workflow is created in `.github/workflows/deploy.yml`.
- The workflow triggers on `push` events to the `main` branch.
- The Vercel token is securely stored as a secret in the GitHub repository.
- The workflow successfully deploys the application to Vercel whenever changes are merged to the `main` branch.

### Additional Information

Please refer to the [Vercel Documentation](https://vercel.com/docs) for detailed instructions on deployment and token generation.

### Assignees

- @ravend3v

### Labels

- deployment
- vercel
- automation

### Milestone

- Automated Deployment Setup
